### ISSUE TITLE
Executable doesn’t have execute permissions.

### ISSUE THREAD

**Issue by harshadgavali** [harshadgavali/gnome-x11-gesture-daemon#2]

**Comment by harshadgavali** [comment]
From https://github.com/harshadgavali/gnome-x11-gesture-daemon/pull/1#issuecomment-908519282

**Comment by harshadgavali** [comment]
@drunckj Tracking issue here.
Does issue still occurs with https://github.com/harshadgavali/gnome-x11-gesture-daemon/releases/tag/git_release

btw you don't need to restart system.
Run inside extracted folder
```
gnome-extensions disable gestureImprovements@gestures
systemctl --user status gesture_improvements_gesture_daemon.service | grep 'Active:'
sh install.sh
systemctl --user daemon-reload
gnome-extensions enable gestureImprovements@gestures
systemctl --user status gesture_improvements_gesture_daemon.service | grep 'Active:'
```

Just to be on safe side, I commented to restart system on README.

**Comment by drunckj** [comment]
> @drunckj Tracking issue here.
> Does issue still occurs with https://github.com/harshadgavali/gnome-x11-gesture-daemon/releases/tag/git_release
> 
> btw you don't need to restart system.
> Run inside extracted folder
> 
> ```
> gnome-extensions disable gestureImprovements@gestures
> systemctl --user status gesture_improvements_gesture_daemon.service | grep 'Active:'
> sh install.sh
> systemctl --user daemon-reload
> gnome-extensions enable gestureImprovements@gestures
> systemctl --user status gesture_improvements_gesture_daemon.service | grep 'Active:'
> ```
> 
> Just to be on safe side, I commented to restart system on README.

The below commands perfectly fine. The service gets started when the extension gets enabled. The user doesn't need to logout and login again. 

The releases zip still requires a logout but it works perfectly after logout. Checked it in 3 vms and it works .Mark the issue as solved.

**Comment by harshadgavali** [comment]
Thanks for confirmation.
