### ISSUE TITLE
Error: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.

### ISSUE THREAD

**Issue by CDG-c0de** [harshadgavali/gnome-x11-gesture-daemon#39]
For some reason the service believes there are multiple ExecStart settings, however in /home/$USER/.config/systemd/user/gesture_improvements_gesture_daemon.service.d/ there is only one override.conf. With one ExecStart definition. I have tried uninstalling with uninstall.sh and reinstalling multiple times. The problem persists. Running systemctl --user daemon-reload does not help. I also tried building and installing from source, no luck. I created the override in the first place because the ExecStart kept referring to root, even though I never installed / ran install.sh in root.

**Comment by harshadgavali** [comment]
Hi @CDG-c0de ,
Sorry for late reply.
I do not know much about systemd config files.
Underlying issue occurs when we run script as `root` first time (even if we run script as non-root in same extracted folder afterwards issue won't get fixed).

To fix follow this steps.
1. Run `uninstall.sh` as both root and non-root
2. Remove override that you have made
3. Delete extracted folder
4. Extract the zip file again
5. Run `install.sh` as non-root

**Comment by CDG-c0de** [comment]
Hey @harshadgavali,
Thank you for replying, I tried the above steps without success.
However this morning the daemon just decided to start working. I don't really know what caused the problem to be resolved, all I have done in the meantime is update/upgrade my packages and install OpenCV...
I don't think this issue is a recurring one, and is just a little bug I was having.
