### ISSUE TITLE
Installer would copy the binary to root folder, although no sudo was used

### ISSUE THREAD

**Issue by donfn** [harshadgavali/gnome-x11-gesture-daemon#42]
In Fedora 37, I tried to install the service and it would copy the binary to /root/bin/.local, although I did run the script as non-root user.
Could it be that the $HOME variable points to root in Fedora? I don't know, it may be interesting to take a look at it/point it out in the README file.

I did fix the service by manually editing it and changing the path to my home folder instead.

![image](https://user-images.githubusercontent.com/12240818/207284384-31bca62f-644c-439c-aefc-2bf0157a5492.png)

**Comment by donfn** [comment]
Probably same as #39

**Comment by harshadgavali** [comment]
@donfn ,
Issue is when we run script `install.sh` as root for first time, It updated `HOME` path to `/root` in service file.
So even if we run script as non-root afterwards, issue won't be fixed.
Instead we need to delete extracted folder and extract it again and install.

I'll fix the script to disallow running as root in next version, (though new version in not planned, cause there aren't any changes yet).
