### ISSUE TITLE
The program just doesn`t start (or crashes)

### ISSUE THREAD

**Issue by g-a-b-r-i-e-l** [harshadgavali/gnome-x11-gesture-daemon#5]
● gesture_improvements_gesture_daemon.service - gesture improvements Gesture Daemon
     Loaded: loaded (/home/gabriel/.config/systemd/user/gesture_improvements_gesture_daemon.service; static)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-01-10 12:22:04 EET; 5ms ago
    Process: 3164 ExecStart=/root/.local/bin/gesture_improvements_gesture_daemon (code=exited, status=203/EXEC)
   Main PID: 3164 (code=exited, status=203/EXEC)
        CPU: 1ms

Jan 10 12:22:04 fedora systemd[1567]: gesture_improvements_gesture_daemon.service: Failed with result 'exit-code'.

**Comment by harshadgavali** [comment]
Hi @g-a-b-r-i-e-l 

ExecStart should be in your local directory not in root.

What is output of `systemctl --user cat gesture_improvements_gesture_daemon.service`?
It should be something like
```
....
ExecStart=/home/........
....
```

Can you check if executable mentioned in `ExecStart` exists?

I'm guessing you installed with `sudo or root`, I have updated README instructing to `**not do that**`.
Can you remove everything installed from using script (3 files) and install `without root or sudo`?

**Comment by harshadgavali** [comment]
Hi @g-a-b-r-i-e-l ,
Assuming this was temporary I'm closing issue.

Please reopen if issue persists after trying what I had suggested.

Thanks.
